version: "3"
services:
  nest:
    image: nest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - .env:/app/.env
    depends_on:
      - db

  nginx:
    image: nginx
    container_name: nest-nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - nest
    environment:
      - NGINX_SERVER_NAME=_
      - NEST_HOST=nest
      - NEST_PORT=3000
      - NGINX_MAX_BODY=100M
    ports:
      - 80:80

  db:
    image: postgres:13.2-alpine
    container_name: nest-db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - nest_db:/var/lib/postgresql/data

volumes:
  nest_db:
