FROM node:lts-alpine as builder

WORKDIR /app

ENV NODE_ENV production
COPY package*.json /app/
RUN set -x && yarn

COPY . /app
RUN set -x && yarn run prestart:prod

EXPOSE 3000

CMD [ "node", "dist/main.js" ]

