services:
  nest:
    image: nest:latest
    environment:
      NODE_ENV: production
    configs:
      - source: nest_env
        target: /app/.env
    networks:
      - app
      - database
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: nest-nginx:latest
    environment:
      NGINX_SERVER_NAME: _
      NEST_HOST: nest
      NEST_PORT: 3000
      NGINX_MAX_BODY: 100M
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
    networks:
      - app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: mariadb:11
    environment:
      MYSQL_DATABASE: nest
      MYSQL_USER: nest
      MYSQL_PASSWORD: nest
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadbdata:/var/lib/mysql
    networks:
      - database
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

configs:
  nest_env:
    file: ./.env

networks:
  app:
  database:

volumes:
  mariadbdata:
